# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7773c5c057ec140871a576d5290fe1178c087ace4a9e671e347ec1368fa6caff7267b4899a4f9d0ce4be36153cc444aa4034ea0c011c6c4ab3535ef61d8d54d2

test:
  secret_key_base: f7d3937e09982663a55792d594eab5a422c8abc973c85722ca612be17fb600c8bef7bebc50e85f89fd1789144a23bf115bd099c9b298051fd8ca2bfe6f18aaf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
